name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18.17.0'

        - name: Install dependencies
          run: npm install

        - name: Build Next.js app
          run: npm run build

        - name: Deploy to Server
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH }}
            SERVER_IP: ${{ secrets.MAVIS_IP }}
            USERNAME: ${{ secrets.MAVIS_USERNAME }}
            PASSPHRASE: ${{ secrets.PASSPHRASE }}
          run: |
            # Write passhprase to temp file 
            echo "$SSH_PRIVATE_KEY" > key.pem
            chmod 600 key.pem
            
            # Use passphrase to enter and deploy build files to server
            sshpass -p "$PASSPHRASE" ssh -o StrictHostKeyChecking=no -i key.pem ${USERNAME}@${SERVER_IP} 'mkdir -p /var/www/wearemavis && scp -r -i key.pem -o StrictHostKeyChecking=no ./next/* ${USERNAME}@${SERVER_IP}:/var/www/wearemavis' || { echo "Deployment failed" >&2; exit 1; }
